name: EnjinNews
main: me.kmecpp.enjinnews.Main
author: kmecpp
version: 0.1
website: dev.bukkit.org/bukkit-plugins/enjin-news/
description:
   Enjin News is a Bukkit plugin which gets news from your servers Enjin website and displays it to players in game!
commands:
   enjinnews:
      description: Displays the help message
   news:
      description: EnjinNews base command
permissions:
   enjinnews.use:
      description: Groups with this permission will be able to use all EnjinNews commands
      default: true
   enjinnews.notify:
      description: Groups with this permission will receive notifications of any new news articles that they have not read
      default: false